name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, looks like it's your first time contributing to the repository, dont't forget to check the CONTRIBUTION.md file in the readme :)"
        pr-message: "Hi there, looks like it's your first time contributing to the repository, dont't forget to check the CONTRIBUTION.md file in the readme :)"
